repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-toml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  - repo: https://github.com/jsh9/pydoclint
    rev: 0.3.8
    hooks:
      - id: pydoclint
        args: [--config=pyproject.toml, -q]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        args: [--strict]
        files: .*py$
        additional_dependencies:
          [
            Flask==3.0.0,
            Flask-Cors==4.0.0,
            apig-wsgi==2.18.0,
            requests==2.31.0,
            icalendar==5.0.11,
            recurring-ical-events==2.1.2,
            types-requests==2.31.0.10,
            types-Flask-Cors==4.0.0.2,
          ]
