version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "icalendar-filter"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
s3_prefix = "icalendar-filter"
image_repositories = ["ICalendarFilterFunction=012346180589.dkr.ecr.eu-west-2.amazonaws.com/icalendarfilter8d25a4e9/icalendarfilterfunction07f70b4erepo"]
